---
data_url: https://covid.ourworldindata.org/data/owid-covid-data.csv

es_host: localhost
es_port: 9200
es_index: covid_data

columns:
  - iso_code
  - continent
  - location
  - date
  - total_cases
  - new_cases
  - total_deaths
  - new_deaths
  - population
  - population_density
  - total_cases_per_million
  - new_cases_per_million
  - total_deaths_per_million
  - new_deaths_per_million
  - total_vaccinations
  - people_vaccinated
  - people_fully_vaccinated
  - new_vaccinations
  - total_vaccinations_per_hundred
  - people_vaccinated_per_hundred
  - people_fully_vaccinated_per_hundred
  - median_age
  - life_expectancy